export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  NOT_FOUND = 'NOT_FOUND',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  EDUCATION_LOAD_FAILED = 'EDUCATION_LOAD_FAILED',
  EDUCATION_CREATE_FAILED = 'EDUCATION_CREATE_FAILED',
  EDUCATION_UPDATE_FAILED = 'EDUCATION_UPDATE_FAILED',
  EDUCATION_DELETE_FAILED = 'EDUCATION_DELETE_FAILED',

  LICENSE_LOAD_FAILED = 'LICENSE_LOAD_FAILED',
  LICENSE_CREATE_FAILED = 'LICENSE_CREATE_FAILED',
  LICENSE_UPDATE_FAILED = 'LICENSE_UPDATE_FAILED',
  LICENSE_DELETE_FAILED = 'LICENSE_DELETE_FAILED',

  PROJECT_LOAD_FAILED = 'PROJECT_LOAD_FAILED',
  PROJECT_CREATE_FAILED = 'PROJECT_CREATE_FAILED',
  PROJECT_UPDATE_FAILED = 'PROJECT_UPDATE_FAILED',
  PROJECT_DELETE_FAILED = 'PROJECT_DELETE_FAILED',

  ABOUT_LOAD_FAILED = 'ABOUT_LOAD_FAILED',
  ABOUT_SAVE_FAILED = 'ABOUT_SAVE_FAILED',

  CONTACT_MISSING_FIELDS = 'CONTACT_MISSING_FIELDS',
  CONTACT_SEND_FAILED = 'CONTACT_SEND_FAILED',
  CONTACT_LOAD_FAILED = 'CONTACT_LOAD_FAILED',
  CONTACT_MARK_READ_FAILED = 'CONTACT_MARK_READ_FAILED',
  CONTACT_DELETE_FAILED = 'CONTACT_DELETE_FAILED',
}